export enum GrassLengths {
  GRASS_LENGTH_MOWED,
  GRASS_LENGTH_CLEAR_0,
  GRASS_LENGTH_CLEAR_1,
  GRASS_LENGTH_CLEAR_2,
  GRASS_LENGTH_CLUMPS_0,
  GRASS_LENGTH_CLUMPS_1,
  GRASS_LENGTH_CLUMPS_2
}
